export declare let ORG_NAME: string
export declare let APP_NAME: string
export declare let APP_PREFIX: string
export declare let DOMAIN_NAME: string
export declare let REGION: string
export declare let API_URL: string
export declare let SERVICE_NAME: string
export declare let DEPLOYMENT_BUCKET_NAME: string
export declare let WEB_APP_BUCKET_NAME: string
export declare let STAGE: string
export declare let DEFAULT_LANGUAGE: string
export declare let USERS_TABLE_NAME: string
export declare let ROLES_TABLE_NAME: string
export declare let USER_ROLES_TABLE_NAME: string
export declare let PERMISSIONS_TABLE_NAME: string
export declare let ROLE_PERMISSIONS_TABLE_NAME: string
export declare let ACCESS_LOGS_TABLE_NAME: string
