name: Deploy

on:
  push:
    branches: [ master, dev, test ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    environment: Test
    
    runs-on: ubuntu-latest

    env:
      STAGE: ${{secrets.STAGE}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      APP_NAME: ${{secrets.APP_NAME}}
      APP_PREFIX: ${{secrets.APP_PREFIX}}
      DEPLOYMENT_BUCKET_NAME: ${{secrets.DEPLOYMENT_BUCKET_NAME}}
      WEB_APP_BUCKET_NAME: ${{secrets.WEB_APP_BUCKET_NAME}}
      DEFAULT_LANGUAGE: ${{secrets.DEFAULT_LANGUAGE}}
      API_URL: ${{secrets.API_URL}}
      APP_URL: ${{secrets.APP_URL}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.28.0
    - run: env
    - run: pnpm run bootstrap
    - run: pnpm run deploy
    - run: pnpm test:integration
