name: Deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: nelonoel/branch-name@v1
      - run: npx pnpm run bootstrap
      - run: npx pnpm run test:integration
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.AWS_REGION }}
          SERVERLESS_ACCESS_KEY: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.SERVERLESS_ACCESS_KEY }}
          APP_NAME: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.APP_NAME }}
          SERVICE_NAME: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.SERVICE_NAME }}
          STAGE: ${{ steps.extract_branch.outputs.branch }}
          REGION: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.AWS_REGION }}
          LANGUAGE: ${{ steps.extract_branch.outputs.branch }}_${{ secrets.LANGUAGE }}
