name: Stage deployment

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: test

    env:
      STAGE: ${{secrets.STAGE}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      APP_NAME: ${{secrets.APP_NAME}}
      APP_PREFIX: ${{secrets.APP_PREFIX}}
      DEPLOYMENT_BUCKET_NAME: ${{secrets.DEPLOYMENT_BUCKET_NAME}}
      WEB_APP_BUCKET_NAME: ${{secrets.WEB_APP_BUCKET_NAME}}
      DEFAULT_LANGUAGE: ${{secrets.DEFAULT_LANGUAGE}}
      API_URL: ${{secrets.API_URL}}
      APP_URL: ${{secrets.APP_URL}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run bootstrap
    - run: pnpm run deploy

  integrationTests:
    needs: deploy

    runs-on: ubuntu-latest

    environment: test

    env:
      STAGE: ${{secrets.STAGE}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      APP_NAME: ${{secrets.APP_NAME}}
      APP_PREFIX: ${{secrets.APP_PREFIX}}
      DEPLOYMENT_BUCKET_NAME: ${{secrets.DEPLOYMENT_BUCKET_NAME}}
      WEB_APP_BUCKET_NAME: ${{secrets.WEB_APP_BUCKET_NAME}}
      DEFAULT_LANGUAGE: ${{secrets.DEFAULT_LANGUAGE}}
      API_URL: ${{secrets.API_URL}}
      APP_URL: ${{secrets.APP_URL}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run bootstrap
    - run: pnpm run build
    - run: pnpm run test:integration
