name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - run: pnpm run bootstrap
      - run: pnpm run build
      - run: pnpm run test:integration
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.AWS_REGION }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          STAGE: test
          LANGUAGE: ${{ secrets.LANGUAGE }}
