name: Stage deployment

on:
  push:
    branches: [ test ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run bootstrap
    - run: pnpm run lint

  deploy:
    needs: lint

    runs-on: ubuntu-latest

    environment: test

    env:
      STAGE: test
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      APP_NAME: juquinha
      APP_PREFIX: ju
      DEPLOYMENT_BUCKET_NAME: ${{secrets.DEPLOYMENT_BUCKET_NAME}}
      WEB_APP_BUCKET_NAME: ${{secrets.WEB_APP_BUCKET_NAME}}
      DEFAULT_LANGUAGE: ${{secrets.DEFAULT_LANGUAGE}}
      API_URL: ${{secrets.API_URL}}
      APP_URL: ${{secrets.APP_URL}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run bootstrap
    - run: pnpm run deploy

  integrationTests:
    needs: deploy

    runs-on: ubuntu-latest

    environment: test

    env:
      STAGE: test
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      APP_NAME: juquinha
      APP_PREFIX: ju
      DEPLOYMENT_BUCKET_NAME: ${{secrets.DEPLOYMENT_BUCKET_NAME}}
      WEB_APP_BUCKET_NAME: ${{secrets.WEB_APP_BUCKET_NAME}}
      DEFAULT_LANGUAGE: ${{secrets.DEFAULT_LANGUAGE}}
      API_URL: ${{secrets.API_URL}}
      APP_URL: ${{secrets.APP_URL}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run bootstrap
    - run: pnpm run build
    - uses: actions/javascript-action@v1
    - uses: ./scripts/actions/test
